package keymap

import (
	"fmt"
	"strings"
)

// RenderMarkdownDoc generates the full KEYBINDINGS.md content from the
// built-in default keymaps — the same source of truth the TUI uses, so the
// doc cannot drift. Columns: Action / Linux·Windows / macOS.
func RenderMarkdownDoc() string {
	lin := Default("linux")
	mac := Default("darwin")

	var b strings.Builder
	b.WriteString("# Keybindings\n\n")
	b.WriteString("> Generated by `log-listener --keybindings-doc` — do not edit by hand.\n")
	b.WriteString("> Run `./build.sh keybindings-docs` (or `build.cmd keybindings-docs` on Windows) to regenerate.\n\n")
	b.WriteString("A terminal TUI cannot capture the macOS Cmd (⌘) key, so macOS bindings ")
	b.WriteString("use the same Ctrl/Shift/Option keys, shown with Mac glyphs.\n\n")

	b.WriteString("| Action | Linux / Windows | macOS | Description |\n")
	b.WriteString("|--------|-----------------|-------|-------------|\n")
	for _, d := range AllActions {
		fmt.Fprintf(&b, "| %s | %s | %s | %s |\n",
			d.Title, lin.Display(d.Action), mac.Display(d.Action), d.Desc)
	}

	b.WriteString("\n## Positional toggles (not individually overridable)\n\n")
	b.WriteString("- `1`–`9` — toggle the corresponding group on/off.\n")
	b.WriteString("- `!@#$%^&*(` (Shift+1..9) — toggle the corresponding renderer on/off.\n")

	b.WriteString("\n## macOS note\n\n")
	b.WriteString("`Ctrl`+Arrow is captured by macOS Mission Control / Spaces, so the macOS ")
	b.WriteString("default advertises `shift+down` / `shift+up` / `shift+left` / `shift+right` ")
	b.WriteString("for fast scrolling (Ctrl+Arrow stays bound as a fallback). ")
	b.WriteString("**Shift+Arrow forwarding to a TUI has not been verified on every macOS ")
	b.WriteString("terminal — if it does nothing, PgUp/PgDn still page.**\n")

	b.WriteString("\n## Overriding keys in your config\n\n")
	b.WriteString("Add a `keybindings:` block to your `log-listener.yml`. Precedence per ")
	b.WriteString("action: current-OS section → `default` section → built-in default. ")
	b.WriteString("A listed action's key list fully replaces the lower layer.\n\n")
	b.WriteString("```yaml\n")
	b.WriteString("keybindings:\n")
	b.WriteString("  default:            # applies on every OS\n")
	b.WriteString("    search: [\"/\"]\n")
	b.WriteString("  darwin:\n")
	b.WriteString("    fast_down: [\"shift+down\"]\n")
	b.WriteString("  linux:\n")
	b.WriteString("    fast_down: [\"ctrl+down\"]\n")
	b.WriteString("  windows:\n")
	b.WriteString("    fast_down: [\"ctrl+down\"]\n")
	b.WriteString("```\n\n")
	b.WriteString("Valid action names: ")
	names := make([]string, len(AllActions))
	for i, d := range AllActions {
		names[i] = "`" + string(d.Action) + "`"
	}
	b.WriteString(strings.Join(names, ", "))
	b.WriteString(".\n")
	return b.String()
}
